### ISSUE TITLE
Weird behavior when switching scene and keyRepeatTimers in place

### ISSUE THREAD

**Issue by Schyzophrenic** [RobertCurry0216/roomy-playdate#2]
Hello, 
I found this odd behavior when switching scene with the usage of the KeyRepeat timers. I have reproduced my issue in this repository, which is a simple as possible. I am not sure what is going on honestly. 
It may be linked to the fact that the code is still executed even after we switch scene, or the timers actually keep a reference to some handlers. 
I would appreciate your input on this matter. Thanks! 

If you run the example in the simulator. Just keep pressing A (holding it). When the counter reaches 11 the Pause Room will be called. It sometimes get stuck here (pressing B to pop the Pause Room will not be taken into account).

https://github.com/Schyzophrenic/keyRepeatRoomy

**Comment by Schyzophrenic** [comment]
I reproduced the issue with the standard SDK, let's close this one out, it is not linked to roomy (even if finding a workaround makes it harder when using roomy)
More information here: https://devforum.play.date/t/keyrepeattimer-fires-one-too-many-times/12438

**Comment by RobertCurry0216** [comment]
I apologize I never got a chance to look into this, but looks like you found the solution 👍🏻

**Comment by Schyzophrenic** [comment]
Well, I haven't found a workaround yet, but I know it's not linked to Roomy now.
